# Generated by Django 4.2.4 on 2024-01-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='photo',
            new_name='pet_photo',
        ),
    ]
